spring:
  application:
    name: Spotify Synchronizer
  main:
    web-environment: false
  datasource:
    url: jdbc:h2:file:~/.ssynchronizer/sync;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

liquibase:
  default-schema: PUBLIC

spotify:
  client-id: 0aada2191351445a8e91aa2b0b9747b8
  endpoints:
    authorization: https://accounts.spotify.com/authorize
    tokens: https://accounts.spotify.com/api/token
    redirect: http://localhost:9600/login
    user-tracks: https://api.spotify.com/v1/me/tracks
