spring:
  application:
    name: Spotify Synchronizer

spotify:
  client-id: 0aada2191351445a8e91aa2b0b9747b8
  endpoints:
    authorization: https://accounts.spotify.com/authorize
    tokens: https://accounts.spotify.com/api/token
    redirect: http://localhost:9600/login
    user-tracks: https://api.spotify.com/v1/me/tracks

synchronizer:
  cache-enabled: true